# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MwQ8vH7hfwNijYl7xfCfGNdg8Iqwptvq
"""

import pandas as pd

cash_request = pd.read_csv("extract - cash request - data analyst.csv")

date_columns = ["created_at", "updated_at", "moderated_at", "reimbursement_date", "cash_request_received_date", "money_back_date", "send_at", "reco_creation", "reco_last_update"]

date_format = '%Y-%m-%d'

for column in date_columns:
    cash_request[column] = pd.to_datetime(cash_request[column], format=date_format, errors='coerce')

print("Data Types After Conversion:")
print(cash_request.dtypes)

